export default{
    MARK_NOTIFICATIONS_BY_ID:'MARK_NOTIFICATIONS_BY_ID',
    MARK_NOTIFICATIONS_BY_ALL:'MARK_NOTIFICATIONS_BY_ALL',
    START_AJAX:'START_AJAX',
    END_AJAX:'END_AJAX',
    SET_LIST:'SET_LIST'
}